<?php
/**
 * Title: GKI Engineering Home Page
 * Slug: gki/home-page
 * Categories: featured
 * Block Types: core/post-content
 */
?>

<!-- wp:html -->
<div id="gki-site">
  <header class="gki-header">
    <div class="gki-container gki-nav">
      <a href="#home" class="gki-logo" aria-label="GKI Engineering home"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/gki-logo-header-v52.avif" alt=""></a>
      <button class="gki-menu-toggle" type="button">Menu</button>
      <ul class="gki-menu">
        <li><a href="#home">Home</a></li><li><a href="#about">About</a></li><li><a href="#services">Services</a></li><li><a href="#projects">Projects</a></li><li><a href="#contact">Contact</a></li>
      </ul>
    </div>
  </header>
  <section class="gki-hero" id="home">
    <div class="gki-container gki-hero-grid">
      <div><div class="gki-eyebrow">GKI Engineering Ltd</div><h1>Reliable maintenance, welding and fabrication solutions.</h1><p class="gki-hero-lead">Commercial kitchen maintenance, commercial facility support, stainless steel welding and bespoke stainless steel fabrication for restaurants, kitchens and commercial buildings.</p><div class="gki-actions"><a class="gki-btn gki-btn-primary" href="#services">Our Services</a><a class="gki-btn gki-btn-secondary" href="#about">Learn More</a></div></div>
      
    </div>
  </section>
  <section class="gki-section" id="about"><div class="gki-container gki-about-grid"><div class="gki-about-media"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/about-kitchen-v52.avif" alt="Commercial kitchen stainless steel maintenance"></div><div class="gki-about-copy"><h2>About GKI Engineering</h2><p>GKI Engineering’s roots date back to 2015, when it began as a venture with a passion for delivering high-quality maintenance works. After years of dedication and hard work, the company was formally registered as GKI Engineering Ltd in May 2022. Our mission has always been to provide exceptional maintenance services for restaurants, kitchens, and commercial buildings, allowing our clients to focus on their core business. We take pride in our attention to detail and commitment to quality, which has earned us a strong reputation in the industry.</p><p>In 2023, we expanded our services to include stainless steel welding and bespoke stainless steel product fabrication, further solidifying our position as a trusted partner for businesses seeking reliable and skilled maintenance solutions. Over the past nine years we’ve proudly served McDonald’s restaurants and many other small businesses across the UK, building strong, long-term relationships in the industry.</p><p>At GKI Engineering Ltd, we’re guided by a simple yet powerful principle: “Do others as you would like to be done to yourself.” This philosophy underpins everything we do, from our work ethic to our client relationships, as we remain committed to delivering exceptional service and building long-term partnerships with our clients.</p></div></div></section>
  <section class="gki-section gki-section-soft" id="services"><div class="gki-container"><h2>Our Services</h2><div class="gki-services gki-services-exact"><div class="gki-service-card"><figure class="gki-service-icon"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/icon-plumbing-v52.svg" alt="Plumbing"></figure><span>Plumbing</span></div><div class="gki-service-card"><figure class="gki-service-icon"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/icon-facilities-v52.svg" alt="Facilities"></figure><span>Facilities</span></div><div class="gki-service-card"><figure class="gki-service-icon"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/icon-welding-v52.svg" alt="Welding"></figure><span>Welding</span></div><div class="gki-service-card"><figure class="gki-service-icon"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/icon-fabrication-v52.svg" alt="Fabrication"></figure><span>Fabrication</span></div></div></div></section>
    <section class="gki-section" id="projects"><div class="gki-container"><h2>Recent Projects</h2><div class="gki-projects"><article class="gki-project"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/project-restaurant-v52.avif" alt="Restaurant maintenance project"><h3>Restaurant Maintenance</h3></article><article class="gki-project"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/project-commercial-v52.avif" alt="Commercial facility project"><h3>Commercial Facility</h3></article><article class="gki-project"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/project-welding-v52.avif" alt="Stainless steel fabrication project"><h3>Stainless Steel Fabrication</h3></article></div></div></section>
  <section class="gki-section gki-dark-section"><div class="gki-container"><h2>Why Choose GKI</h2><div class="gki-why"><div class="gki-why-item"><span class="gki-why-icon gki-why-professionals"></span><div><strong>Professionals</strong><p>Skilled and experienced engineers.</p></div></div><div class="gki-why-item"><span class="gki-why-icon gki-why-reliable"></span><div><strong>Reliable Solutions</strong><p>Delivering dependable results every time.</p></div></div><div class="gki-why-item"><span class="gki-why-icon gki-why-detail"></span><div><strong>Detail Driven</strong><p>Precision and attention in every project.</p></div></div><div class="gki-why-item"><span class="gki-why-icon gki-why-partners"></span><div><strong>Long-Term Partners</strong><p>Building lasting relationships with our clients.</p></div></div></div><div class="gki-info-row"><div class="gki-info-card gki-testimonials"><h2>Testimonials</h2><div class="gki-swiper"><div class="gki-slides"><article class="gki-testimonial-card"><p>Excellent support for our kitchen maintenance needs. Fast response, tidy workmanship and clear communication from start to finish.</p><cite>Restaurant Manager</cite></article><article class="gki-testimonial-card"><p>GKI Engineering helped us with stainless steel fabrication and the finished product was clean, strong and exactly to specification.</p><cite>Commercial Kitchen Client</cite></article><article class="gki-testimonial-card"><p>A reliable maintenance partner for commercial building works. Professional, punctual and focused on long-term service quality.</p><cite>Facilities Client</cite></article></div></div><div class="gki-slider-menu" aria-label="Testimonials slider menu"></div></div><div class="gki-info-card gki-coverage-card"><h2>Coverage Services</h2><p>Based in Birmingham, GKI Engineering provides commercial kitchen maintenance, facility support, stainless steel welding and bespoke fabrication services across the Midlands and London.</p><div class="gki-coverage"><span class="gki-chip">Midlands</span><span class="gki-chip">London</span></div></div></div></div></section>
  <section class="gki-section" id="contact"><div class="gki-container"><h2>Contact Us</h2><div class="gki-contact-grid"><div class="gki-form-card">
<!-- /wp:html -->
<!-- wp:wpbb/dynamic-form {"formTitle":"Contact Us","recipient":"guntis@gkiengineering.co.uk","emailSubject":"New GKI Engineering website enquiry","successMessage":"Thank you. Your message has been sent.","submitText":"Send Message","showTitle":false,"formClass":"gki-bbuilder-form","buttonClass":"btn btn-primary gki-btn gki-btn-primary","stylePreset":"default","labelPosition":"top","gap":3,"fieldsJson":"[{\"type\":\"text\",\"name\":\"name\",\"label\":\"Name\",\"required\":true,\"width\":6,\"placeholder\":\"Name\",\"step\":1},{\"type\":\"phone\",\"name\":\"phone\",\"label\":\"Phone\",\"required\":false,\"width\":6,\"placeholder\":\"Phone\",\"step\":1},{\"type\":\"email\",\"name\":\"email\",\"label\":\"Email\",\"required\":true,\"width\":12,\"placeholder\":\"Email\",\"step\":1},{\"type\":\"textarea\",\"name\":\"message\",\"label\":\"Message\",\"required\":true,\"width\":12,\"placeholder\":\"Message\",\"step\":1}]"} /-->
<!-- wp:html -->
</div><div class="gki-contact-card"><div class="gki-map"><iframe src="https://www.google.com/maps?q=116+Yardley+Road,+Acocks+Green,+Birmingham,+B27+6LG&output=embed" loading="lazy" allowfullscreen referrerpolicy="no-referrer-when-downgrade" title="GKI Engineering Ltd Google Map"></iframe></div><div class="gki-contact-details"><strong>GKI Engineering Ltd</strong><p>116 Yardley Road<br>Acocks Green<br>Birmingham, England<br>B27 6LG</p><p><a href="https://find-and-update.company-information.service.gov.uk/company/14112841" target="_blank" rel="noopener noreferrer">Registered in England & Wales · Company No. 14112841</a></p></div></div></div></div></section>
  <footer class="gki-footer"><div class="gki-container">© <span class="gki-current-year">2026</span> GKI Engineering Ltd. All rights reserved. · <a href="https://find-and-update.company-information.service.gov.uk/company/14112841" target="_blank" rel="noopener noreferrer">Company No. 14112841</a></div></footer><script id="gki-current-year-template-v53">document.querySelectorAll(".gki-current-year").forEach(function(el){el.textContent=(new Date()).getFullYear();});</script>
  <button class="gki-scrolltop" type="button" aria-label="Scroll to top"><svg viewBox="0 0 24 24"><path d="M12 19V5M5 12l7-7 7 7"/></svg></button>
</div>
<!-- /wp:html -->