<?php
/**
 * Title: GKI Engineering Home Page
 * Slug: gki/home-page
 * Categories: featured
 * Block Types: core/post-content
 */
?>

<!-- wp:html -->
<div id="gki-site">
  <header class="gki-header">
    <div class="gki-container gki-nav">
      <a href="#home" class="gki-logo" aria-label="GKI Engineering home"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/gki-logo.png" alt=""></a>
      <button class="gki-menu-toggle" type="button">Menu</button>
      <ul class="gki-menu">
        <li><a href="#home">Home</a></li><li><a href="#about">About</a></li><li><a href="#services">Services</a></li><li><a href="#projects">Projects</a></li><li><a href="#contact">Contact</a></li>
      </ul>
    </div>
  </header>
  <section class="gki-hero" id="home">
    <div class="gki-container gki-hero-grid">
      <div><div class="gki-eyebrow">GKI Engineering Ltd</div><h1>Reliable maintenance, welding and fabrication solutions.</h1><p class="gki-hero-lead">Commercial kitchen maintenance, commercial facility support, stainless steel welding and bespoke stainless steel fabrication for restaurants, kitchens and commercial buildings.</p><div class="gki-actions"><a class="gki-btn gki-btn-primary" href="#services">Our Services</a><a class="gki-btn gki-btn-secondary" href="#about">Learn More</a></div></div>
      <figure class="hero-card"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/hero-realistic-final-v22.jpg" alt="GKI Engineering team and trade van for commercial maintenance"></figure>
    </div>
  </section>
  <section class="gki-section" id="about"><div class="gki-container gki-about-grid"><div class="gki-about-media"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/project-restaurant-final-v22.jpg" alt="Commercial kitchen stainless steel maintenance"></div><div class="gki-about-copy"><h2>About GKI Engineering</h2><p>GKI Engineering’s roots date back to 2015, when it began as a venture with a passion for delivering high-quality maintenance works. After years of dedication and hard work, the company was formally registered as GKI Engineering Ltd in May 2022. Our mission has always been to provide exceptional maintenance services for restaurants, kitchens, and commercial buildings, allowing our clients to focus on their core business. We take pride in our attention to detail and commitment to quality, which has earned us a strong reputation in the industry.</p><p>In 2023, we expanded our services to include stainless steel welding and bespoke stainless steel product fabrication, further solidifying our position as a trusted partner for businesses seeking reliable and skilled maintenance solutions. Over the past nine years we’ve proudly served McDonald’s restaurants and many other small businesses across the UK, building strong, long-term relationships in the industry.</p><p>At GKI Engineering Ltd, we’re guided by a simple yet powerful principle: “Do others as you would like to be done to yourself.” This philosophy underpins everything we do, from our work ethic to our client relationships, as we remain committed to delivering exceptional service and building long-term partnerships with our clients.</p></div></div></section>
  <section class="gki-section gki-section-soft" id="services"><div class="gki-container"><h2>Our Services</h2><div class="gki-services"><div class="gki-service-card"><svg viewBox="0 0 64 64"><path d="M14 8h18v10H14zM23 18v12c0 7 5 12 12 12h7v10h-9c-13 0-22-9-22-22V18z"/><path d="M43 42h9v10h-9zM42 47h-9"/><path d="M38 10l8 8m0 0l8-8m-8 8v18"/></svg><span>Plumbing</span></div><div class="gki-service-card"><svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="9"/><path d="M32 6v9M32 49v9M6 32h9M49 32h9M13.6 13.6l6.4 6.4M44 44l6.4 6.4M50.4 13.6L44 20M20 44l-6.4 6.4"/><path d="M25 8l14 0 3 7 7 3 7-3 0 14-7 3-3 7 3 7-14 0-3-7-7-3-7 3 0-14 7-3 3-7z"/></svg><span>Mechanical</span></div><div class="gki-service-card"><svg viewBox="0 0 64 64"><path d="M10 54h44M14 54V22l14-8v40M28 54V10h22v44"/><path d="M18 30h5M18 38h5M18 46h5M34 18h5M34 28h5M34 38h5M44 18h3M44 28h3M44 38h3"/></svg><span>Facility</span></div><div class="gki-service-card"><svg viewBox="0 0 64 64"><path d="M15 14h22l6 9-5 23H14L9 23z"/><path d="M19 25h18v10H19zM46 43l8 8M50 39l6-2M42 50l-2 6M48 49l5 2"/><path d="M43 43l8-8"/></svg><span>Welding</span></div><div class="gki-service-card"><svg viewBox="0 0 64 64"><path d="M32 6l23 13v26L32 58 9 45V19z"/><path d="M32 6v26l23-13M32 32L9 19M32 32v26M18 24l28 16M46 24L18 40"/></svg><span>Fabrication</span></div></div></div></section>
  <section class="gki-section" id="projects"><div class="gki-container"><h2>Recent Projects</h2><div class="gki-projects"><article class="gki-project"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/project-restaurant-final-v22.jpg" alt="Restaurant maintenance project"><h3>Restaurant Maintenance</h3></article><article class="gki-project"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/project-commercial-final-v22.jpg" alt="Commercial facility project"><h3>Commercial Facility</h3></article><article class="gki-project"><img src="/wp-content/themes/wp-bbtheme-child-gki/assets/gki/project-welding-final-v22.jpg" alt="Stainless steel fabrication project"><h3>Stainless Steel Fabrication</h3></article></div></div></section>
  <section class="gki-section gki-dark-section"><div class="gki-container"><h2>Why Choose GKI</h2><div class="gki-why"><div class="gki-why-item"><span class="gki-why-icon"><svg viewBox="0 0 24 24"><path d="M20 6L9 17l-5-5"/></svg></span><strong>Professionals</strong></div><div class="gki-why-item"><span class="gki-why-icon"><svg viewBox="0 0 24 24"><path d="M9 18h6M10 22h4M12 2a7 7 0 0 0-4 12c1 1 1.5 2 1.5 3h5c0-1 .5-2 1.5-3a7 7 0 0 0-4-12z"/></svg></span><strong>Reliable Solutions</strong></div><div class="gki-why-item"><span class="gki-why-icon"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="M21 21l-5-5M11 8v6M8 11h6"/></svg></span><strong>Detail Driven</strong></div><div class="gki-why-item"><span class="gki-why-icon"><svg viewBox="0 0 24 24"><path d="M8 12l3 3 5-6"/><path d="M3 12a9 9 0 1 0 18 0 9 9 0 0 0-18 0z"/></svg></span><strong>Long-Term Partners</strong></div></div></div></section>
  <section class="gki-section gki-testimonials"><div class="gki-container"><h2>Testimonials</h2><div class="gki-swiper"><div class="gki-slides"><article class="gki-testimonial-card"><p>Excellent support for our kitchen maintenance needs. Fast response, tidy workmanship and clear communication from start to finish.</p><cite>Restaurant Manager</cite></article><article class="gki-testimonial-card"><p>GKI Engineering helped us with stainless steel fabrication and the finished product was clean, strong and exactly to specification.</p><cite>Commercial Kitchen Client</cite></article><article class="gki-testimonial-card"><p>A reliable maintenance partner for commercial building works. Professional, punctual and focused on long-term service quality.</p><cite>Facilities Client</cite></article></div></div><div class="gki-slider-menu" aria-label="Testimonials slider menu"></div></div></section>
  <section class="gki-section gki-section-soft"><div class="gki-container"><h2>Coverage Services</h2><p>Based in Birmingham, GKI Engineering provides commercial kitchen maintenance, facility support, stainless steel welding and bespoke fabrication services across the Midlands and London.</p><div class="gki-coverage"><span class="gki-chip">Midlands</span><span class="gki-chip">London</span></div></div></section>
  <section class="gki-section" id="contact"><div class="gki-container"><h2>Contact Us</h2><div class="gki-contact-grid"><div class="gki-form-card">
<!-- /wp:html -->
<!-- wp:wpbb/dynamic-form {"formTitle":"Contact Us","recipient":"guntis@gkiengineering.co.uk","emailSubject":"New GKI Engineering website enquiry","successMessage":"Thank you. Your message has been sent.","submitText":"Send Message","showTitle":false,"formClass":"gki-bbuilder-form","buttonClass":"btn btn-primary gki-btn gki-btn-primary","stylePreset":"default","labelPosition":"top","gap":3,"fieldsJson":"[{\"type\":\"text\",\"name\":\"name\",\"label\":\"Name\",\"required\":true,\"width\":6,\"placeholder\":\"Name\",\"step\":1},{\"type\":\"phone\",\"name\":\"phone\",\"label\":\"Phone\",\"required\":false,\"width\":6,\"placeholder\":\"Phone\",\"step\":1},{\"type\":\"email\",\"name\":\"email\",\"label\":\"Email\",\"required\":true,\"width\":6,\"placeholder\":\"Email\",\"step\":1},{\"type\":\"text\",\"name\":\"subject\",\"label\":\"Subject\",\"required\":false,\"width\":6,\"placeholder\":\"Subject\",\"step\":1},{\"type\":\"textarea\",\"name\":\"message\",\"label\":\"Message\",\"required\":true,\"width\":12,\"placeholder\":\"Message\",\"step\":1}]"} /-->
<!-- wp:html -->
</div><div class="gki-contact-card"><div class="gki-map"><iframe src="https://www.google.com/maps?q=116+Yardley+Road,+Acocks+Green,+Birmingham,+B27+6LG&output=embed" loading="lazy" allowfullscreen referrerpolicy="no-referrer-when-downgrade" title="GKI Engineering Ltd Google Map"></iframe></div><div class="gki-contact-details"><strong>GKI Engineering Ltd</strong><p>116 Yardley Road<br>Acocks Green<br>Birmingham, England<br>B27 6LG<br>Phone: <a href="tel:+447760660983">+44 (0) 7760660983</a></p><p><a href="https://find-and-update.company-information.service.gov.uk/company/14112841" target="_blank" rel="noopener noreferrer">Registered in England & Wales · Company No. 14112841</a></p></div></div></div></div></section>
  <footer class="gki-footer"><div class="gki-container">© 2026 GKI Engineering Ltd. All rights reserved. · <a href="https://find-and-update.company-information.service.gov.uk/company/14112841" target="_blank" rel="noopener noreferrer">Company No. 14112841</a></div></footer>
  <button class="gki-scrolltop" type="button" aria-label="Scroll to top"><svg viewBox="0 0 24 24"><path d="M12 19V5M5 12l7-7 7 7"/></svg></button>
</div>
<!-- /wp:html -->